#!/usr/bin/env perl

# Looks for .yml files under `workflow-templates` and processes #include
# directives therein. The results of processing workflow-templates/foo.yml
# are written to .github/workflows/foo.yml.
#
# Syntax:
#
# #include foo
#
#   includes the file `foo`, if it can be found in workflow-templates, or
#   $standard_template_directory/foo, and fails hard if neither can be found.
#   The contents of foo are indented exactly as the #include directive is.
#
# #include foo || bar
#
#   As above, except if neither a project-specific foo or a foo from the
#   standard template directory can be found, goes on to similarly look for bar
#   in both places. If bar can't be found in either, it fails hard. As a
#   special case, it won't even try to read a file called `null` and will
#   pretend it succeeded.
#
#   This means that as well as over-riding a default with ... || bar you can
#   implement an optional include with ... || null
#
# $template_var{variable_name}
#
#   Replaced with the contents of a variable. Variables are created by
#   providing them as arguments to #include thus:
#
#     #include foo.inc colour = "red" texture = "smooth" ... [|| ...]
#
#   There is a special variable workflow_file_name that always evaluates to the
#   name of the file currently being processed, with any extention chopped off,
#   so in this example it would be "foo".
#
#   Tnd then in the included template:
#
#       #include $template_var{workflow_file_name}/bar.inc
#       steps:
#         uses: colour/$template_var{colour}
#
#   that would result in:
#
#       #include foo/bar.inc
#       steps:
#         uses: colour/red
#
#   If a variable isn't defined then a default can be given. The default can be
#   null just like in #include:
#
#       name: $template_var{name} || "default name"

use strict;
use warnings;

use Cwd;
use File::Basename;
use File::Find::Rule;
use File::Slurp;

# need to find this binary, so we can find the nearby templates
my $this_binary = $0;
# resolve symlinks
if(-l $this_binary) {
    my $link_target = readlink($this_binary);
    if(index($link_target, '/') == 0) {
        $this_binary = $link_target;
    } else {
        $this_binary = join('/', dirname($this_binary), $link_target);
    }
}
# turn relative path into absolute
if(index($this_binary, '/') != 0) {
    $this_binary = join('/', getcwd, $this_binary);
}
my $shared_template_dir = join('/', dirname($this_binary), 'standard-templates');
die("Can't find standard templates for $this_binary\n")
    unless(-d $shared_template_dir);

die("This should be run from the root of a git checkout, which has .github/workflows and workflow-templates\n")
    unless(-d '.github/workflows' && -d 'workflow-templates');

chdir('workflow-templates');

my $include_re = qr/^(\s*)#include\s+(\S+)(.*)$/;

foreach my $root_template (
    File::Find::Rule
        ->file
        ->name('*.yml')
        ->in('.')
) {
    print "Processing workflow-templates/$root_template\n";
    open(my $fh, '<', $root_template) || die("Couldn't read workflow-templates/$root_template: $!\n");
    my @lines = process(
        {
            workflow_file_name => basename($root_template, '.yml'),
        },
        <$fh>,
    );
    close($fh);

    print "Writing to .github/workflows/$root_template\n";
    open($fh, '>', "../.github/workflows/$root_template") || die("Couldn't write .github/workflows/$root_template\n");
    print $fh "# Auto-generated file, see workflow-templates/$root_template\n";
    print $fh "# To rebuild, see rebuild-workflows in https://github.com/DrHyde/meta-perlmodules\n\n";
    print $fh grep { /\S/ } @lines;
    close($fh);
}

sub process {
    my($template_vars, @input_lines) = @_;
    my @output_lines = ();

    foreach my $line (@input_lines) {
        my $include = parse_include($line, $template_vars);
        if($include) {
            print "  found #include: $include->{filename}".
                  ($include->{alternative} ? " || $include->{alternative}" : '').
                  "\n"
                if($ENV{REBUILD_WORKFLOW_DEBUG});
            my $done_include = 0;
            my %child_template_vars = (%{$template_vars}, %{$include->{vars}});
            foreach my $candidate_file (
                map {
                    $_, join('/', $shared_template_dir, $_)
                } grep { defined($_) && length($_) } ($include->{filename}, $include->{alternative})
            ) {
                if($candidate_file eq 'null') {
                    print "    processed 'null'\n" if($ENV{REBUILD_WORKFLOW_DEBUG});
                    $done_include = 1;
                    last;
                }
                my @included_lines = read_include($candidate_file);
                next if(!@included_lines);

                push @output_lines, map { $include->{indent}.$_ } process(\%child_template_vars, @included_lines);
                print "    processed $candidate_file\n" if($ENV{REBUILD_WORKFLOW_DEBUG});
                $done_include = 1;
                last;
            }
            die("Couldn't #include $include->{filename}\n") unless($done_include);
        } else {
            push @output_lines, interpolate_template_vars($line, $template_vars);
        }
    }

    return @output_lines;
}

sub read_include {
    my $file = shift;
    if(!-f $file || !-r $file) { return (); }
    open(my $fh, '<', $file) || die("Can't read $file: $!");  # uncoverable branch true note: read_include only reaches open() after -f and -r checks, and forcing a real open failure here is not worth a fixture
    my @lines = <$fh>;
    if(@lines && $ENV{REBUILD_WORKFLOW_DEBUG}) {
        unshift @lines, "# included from $file\n";
        push @lines, "# end include\n";
    }
    return @lines;
}

sub parse_include {
    my($line, $template_vars) = @_;
    return unless($line =~ /$include_re/);

    my($indent, $filename, $remainder) = ($1, $2, $3);
    my @tokens = tokenize_include_remainder($remainder, $line);
    my %include_vars = ();
    my $alternative;

    while(@tokens) {
        my $token = shift(@tokens);
        if($token eq '||') {
            $alternative = shift(@tokens);
            die("Missing fallback in #include line: $line") unless(defined($alternative));
            die("Unexpected tokens after fallback in #include line: $line") if(@tokens);
            last;
        }

        die("Invalid template variable name '$token' in #include line: $line")
            unless($token =~ /^[A-Za-z_][A-Za-z0-9_]*$/);

        my $equals = shift(@tokens);
        my $value  = shift(@tokens);
        die("Expected '=' after $token in #include line: $line")
            unless(defined($equals) && $equals eq '=');
        die("Missing value for $token in #include line: $line")
            unless(defined($value));

        $include_vars{$token} = interpolate_template_vars($value, $template_vars);
    }

    return {
        indent      => $indent,
        filename    => interpolate_template_vars($filename, $template_vars),
        alternative => defined($alternative)
            ? interpolate_template_vars($alternative, $template_vars)
            : undef,
        vars        => \%include_vars,
    };
}

sub tokenize_include_remainder {
    my($remainder, $line) = @_;
    my @tokens = ();
    pos($remainder) = 0;

    while($remainder =~ /\G\s*(\|\||=|"((?:[^"\\]|\\.)*)"|(\S+))/gc) {
        if(defined($2)) {
            push @tokens, unescape_quoted($2);
        } else {
            push @tokens, $1;
        }
    }

    return @tokens;
}

sub interpolate_template_vars {
    my($text, $template_vars) = @_;
    my $original_text = $text;

    $text =~ s{
        \$template_var\{([A-Za-z_][A-Za-z0-9_]*)\}
        (?:\s*\|\|\s*(null|"((?:[^"\\]|\\.)*)"))?
    }{
        resolve_template_var($1, defined($2) ? $2 : undef, $template_vars, $original_text)
    }gex;

    return $text;
}

sub resolve_template_var {
    my($name, $default, $template_vars, $line) = @_;
    return $template_vars->{$name} if(exists($template_vars->{$name}));

    if(defined($default)) {
        return q{} if($default eq 'null');
        return unescape_quoted(substr($default, 1, -1));
    }

    die("Undefined template variable '$name' in line: $line");
}

sub unescape_quoted {
    my $value = shift;
    $value =~ s/\\(.)/$1/g;
    return $value;
}
