#!/usr/bin/env perl

# Looks for .yml files under `workflow-templates` and processes #include
# directives therein. The results of processing workflow-templates/foo.yml
# are written to .github/workflows/foo.yml.
#
# Syntax:
#
# #include foo
#
# includes the file `foo`, if it can be found in workflow-templates, or
# $standard_template_directory/foo, and fails hard if neither can be found.
# The contents of foo are indented exactly as the #include directive is.
#
# #include foo || bar
#
# As above, except if neither a project-specific foo or a foo from the standard
# template directory can be found, goes on to similarly look for bar in both
# places. If bar can't be found in either, it fails hard. As a special case,
# it won't even try to read a file called `null` and will pretend it succeeded.
#
# This means that as well as over-riding a default with ... || bar you can
# implement an optional include with ... || null

use strict;
use warnings;

use Cwd;
use File::Basename;
use File::Find::Rule;
use File::Slurp;

# need to find this binary, so we can find the nearby templates
my $this_binary = $0;
# resolve symlinks
if(-l $this_binary) {
    my $link_target = readlink($this_binary);
    if(index($link_target, '/') == 0) {
        $this_binary = $link_target;
    } else {
        $this_binary = join('/', dirname($this_binary), $link_target);
    }
}
# turn relative path into absolute
if(index($this_binary, '/') != 0) {
    $this_binary = join('/', getcwd, $this_binary);
}
my $shared_template_dir = join('/', dirname($this_binary), 'standard-templates');
die("Can't find standard templates for $this_binary\n")
    unless(-d $shared_template_dir);

die("This should be run from the root of a git checkout, which has .github/workflows and workflow-templates\n")
    unless(-d '.github/workflows' && -d 'workflow-templates');

chdir('workflow-templates');

my $include_re = qr/^(\s*)#include\s+(\S+)(?:\s+\|\|\s+(\S+))?/;

foreach my $root_template (
    File::Find::Rule
        ->file
        ->name('*.yml')
        ->in('.')
) {
    print "Processing workflow-templates/$root_template\n";
    open(my $fh, '<', $root_template) || die("Couldn't read workflow-templates/$root_template: $!\n");
    my @lines = process('  ', <$fh>);
    close($fh);

    print "Writing to .github/workflows/$root_template\n";
    open($fh, '>', "../.github/workflows/$root_template") || die("Couldn't write .github/workflows/$root_template\n");
    print $fh "# Auto-generated file, see workflow-templates/$root_template\n\n";
    print $fh grep { /\S/ } @lines;
    close($fh);
}

sub process {
    my $diags_indent = shift;
    my @input_lines  = @_;
    my @output_lines = ();

    foreach my $line (@input_lines) {
        if($line =~ /$include_re/) {
            my($indent, $filename, $alternative) = ($1, $2, $3);
            print "${diags_indent}found #include: $filename".
                  ($alternative ? " || $alternative" : '').
                  "\n";
            my $done_include = 0;
            foreach my $candidate_file (
                map {
                    $_, join('/', $shared_template_dir, $_)
                } grep { $_ } ($filename, $alternative)
            ) {
                if($candidate_file eq 'null') {
                    $done_include = 1;
                    last;
                }
                my @included_lines = read_include($candidate_file);
                next if(!@included_lines);

                push @output_lines, map { $indent.$_ } @included_lines;
                $done_include = 1;
                last;
            }
            die("Couldn't #include $filename\n") unless($done_include);
        } else {
            push @output_lines, $line
        }
    }
    if(grep { /$include_re/ } @output_lines) {
        @output_lines = process("$diags_indent  ", @output_lines);
    }

    return @output_lines;
}

sub read_include {
    my $file = shift;
    if(!-f $file || !-r $file) { return (); }
    open(my $fh, '<', $file) || die("Can't read $file: $!");
    return <$fh>;
}
